### ISSUE TITLE
Implement media entity crud

### ISSUE THREAD

**Issue by yrodez** [open-digital-solutions/opencrm#1]
Media entity will be used to store all system files.

Files on the system should be:
- Uploaded
- Edited properties
- Deleted

Please implement all needed pages to archive ths features using bootstrap 5 ui components. 

The pages and services most ge implemented on the Web Core project to allow his use on all modules and Web Head project.

The main data file service most be implemented on the core project to allow his use on any other project.

**Comment by denebMM** [comment]
25hr
